//! Code Generator - Generate ALN schemas from templates
//!
//! This module provides code generation for ALN manifests,
//! Sourzes, and other artifacts from templates.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::Utc;
use std::path::Path;

/// ALN code generator
pub struct AlnGenerator {
    template_dir: Option<String>,
    output_dir: Option<String>,
}

/// Generation request
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateRequest {
    pub artifact_type: String,
    pub name: String,
    pub capabilities: Vec<String>,
    pub output_path: String,
}

/// Generation result
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GenerateResult {
    pub success: bool,
    pub output_path: String,
    pub generated_files: Vec<String>,
    pub warnings: Vec<String>,
}

impl AlnGenerator {
    /// Create a new generator
    pub fn new() -> Self {
        Self {
            template_dir: None,
            output_dir: None,
        }
    }

    /// Set template directory
    pub fn with_template_dir(mut self, path: &str) -> Self {
        self.template_dir = Some(path.to_string());
        self
    }

    /// Set output directory
    pub fn with_output_dir(mut self, path: &str) -> Self {
        self.output_dir = Some(path.to_string());
        self
    }

    /// Generate a Sourze manifest
    pub fn generate_sourze(&self, request: &GenerateRequest) -> Result<GenerateResult, crate::error::DevToolsError> {
        let output_path = Path::new(&request.output_path);
        
        // Create parent directories
        if let Some(parent) = output_path.parent() {
            std::fs::create_dir_all(parent)?;
        }

        // Generate manifest content
        let manifest = self.create_sourze_manifest(request)?;
        
        // Write to file
        std::fs::write(output_path, &manifest)?;

        Ok(GenerateResult {
            success: true,
            output_path: request.output_path.clone(),
            generated_files: vec![request.output_path.clone()],
            warnings: vec![],
        })
    }

    /// Create Sourze manifest content
    fn create_sourze_manifest(&self, request: &GenerateRequest) -> Result<String, crate::error::DevToolsError> {
        let manifest_id = Uuid::new_v4().to_string();
        let timestamp = Utc::now().timestamp();
        
        // Default capabilities (safe defaults)
        let capabilities = if request.capabilities.is_empty() {
            vec!["NETCLIENT".to_string(), "FSREAD".to_string()]
        } else {
            request.capabilities.clone()
        };

        let content = format!(
            r#"# ALN Sourze Manifest
# Generated by aln-dev-tools
# DO NOT EDIT MANUALLY

manifest_id: {}
name: {}
timestamp: {}
capabilities:
{}
eco_vector:
  gco2_per_joule: 0.001
  eco_impact_score: 0.5
  energy_autonomy_pct: 0.8
  eco_floor_minimum: 0.3
ndm_ceiling: 0.3
non_weapon_envelope:
  envelope_id: {}
  permitted_missions:
    - ecological_restoration
    - clinical_assistive_care
    - diagnostics
  forbidden_missions:
    - kinetic_damage
    - crowd_control
    - weapon_deployment
  requires_multi_sig: true
"#,
            manifest_id,
            request.name,
            timestamp,
            capabilities.iter().map(|c| format!("  - {}", c)).collect::<Vec<_>>().join("\n"),
            Uuid::new_v4().to_string(),
        );

        Ok(content)
    }

    /// Generate project template
    pub fn generate_project(&self, name: &str, output_dir: &str) -> Result<GenerateResult, crate::error::DevToolsError> {
        // Create project structure
        let project_path = Path::new(output_dir).join(name);
        std::fs::create_dir_all(&project_path)?;
        std::fs::create_dir_all(project_path.join("src"))?;
        std::fs::create_dir_all(project_path.join("config"))?;
        std::fs::create_dir_all(project_path.join("tests"))?;

        // Create default files
        let manifest_path = project_path.join("manifest.aln");
        let request = GenerateRequest {
            artifact_type: "sourze".to_string(),
            name: name.to_string(),
            capabilities: vec![],
            output_path: manifest_path.to_string_lossy().to_string(),
        };

        self.generate_sourze(&request)
    }
}

impl Default for AlnGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    #[test]
    fn test_generator_creation() {
        let generator = AlnGenerator::new();
        assert!(generator.template_dir.is_none());
    }

    #[test]
    fn test_sourze_generation() {
        let dir = tempdir().unwrap();
        let output_path = dir.path().join("manifest.aln").to_string_lossy().to_string();
        
        let generator = AlnGenerator::new();
        let request = GenerateRequest {
            artifact_type: "sourze".to_string(),
            name: "test-sourze".to_string(),
            capabilities: vec!["NETCLIENT".to_string()],
            output_path,
        };

        let result = generator.generate_sourze(&request);
        assert!(result.is_ok());
    }
}
